# Jekyll Configuration File

# Site settings
title: Hanieh Rashidpour
email: example@example.com
description: >-
  A personal website showcasing research, publications, and education.
baseurl: "/hanieh-rashidpour" # Adjusted for subdirectory deployment
url: "https://hrashidpour.github.io" 

# Build settings
markdown: kramdown
permalink: pretty
source: ./src
destination: ./_site

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files and folders from the build
exclude:
  - node_modules
  - .git
  - .github
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - vite.config.ts
  - tsconfig.json
  - tsconfig.app.json
  - tsconfig.node.json
